# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Wno-deprecated-declarations -std=c17 -O2
CXXFLAGS = -Wall -Wextra -Wno-deprecated-declarations -std=c++20 -O2

PREFER_OS_LIBC = NO

# ----------------------------

include $(shell cedev-config --makefile)
